### ISSUE TITLE
Suggested edit for PGP/Importing_keys

### ISSUE THREAD

**Issue by sean9999** [Yubico/developers.yubico.com#18]
in the introduction when `ykneo-openpgp` is mentioned, please link it do a download, so uses like me can find the software more easily

**Comment by minisu** [comment]
The [ykneo-openpgp applet](https://github.com/Yubico/ykneo-openpgp) is already installed on all YubiKeys supporting it. There are no downloads required (in fact users cannot install applets on their YubiKeys at all).

Maybe we should consider going the opposite direction. That is, not mentioning _"ykneo-openpgp"_ or _"applet"_ since those things does not help the user (they rather create confusion). What do you think?

**Comment by sean9999** [comment]
that sounds fair
