### ISSUE TITLE
Redirect links to SSH Configuration contain potential malware links

### ISSUE THREAD

**Issue by KrishnaIyer** [Yubico/developers.yubico.com#182]
Hello Guys,

The links for the SSH configuration guides for different platforms contain potentially malicious links:
https://developers.yubico.com/PGP/SSH_authentication/
Ex: The link for `OSX` directs to  `http://florin.myip.org/blog/easy-multifactor-authentication-ssh-using-yubikey-neo-tokens` which is flagged as malware by `AVG`.

<img width="606" alt="Yubico" src="https://user-images.githubusercontent.com/13186113/57454145-782ea980-7268-11e9-9ada-62a8844546b3.png">

 `myip.org` is a dynamic DNS Service so perhaps the link was carried over from the dev environment?

I can create a PR with a fix if I get some time soon.

Thanks,
Krishna

**Comment by nevun** [comment]
Could you find out why AVG think that page contains mailware?

No one else thinks so: https://www.virustotal.com/#/url/e14372e841c8364895ab36861190fcf2ce3d59ec6756cf4bd26419d1523c23ae/detection

You might have been the victim of a local network spoofing attack which is possible since the page is served over http. The link should be using https though.
