### ISSUE TITLE
Suggested edit for U2F/Attestation_and_Metadata/index

### ISSUE THREAD

**Issue by zackify** [Yubico/developers.yubico.com#261]
Yubikey 5c hex appears to be: 0410cb69481e8ff7403993ec0a2729a154a8

This document doesn't include the 5c in it, so I'm not 100% sure if I'm correct.

https://developers.yubico.com/U2F/yubico-metadata.json

---
See https://developers.yubico.com/U2F/Attestation_and_Metadata/

**Comment by emlun** [comment]
Thanks, but YubiKey 5C falls under the "YubiKey 5 Series security key" umbrella, whose AAGUID is a suffix of the one above. Looks like your hex string also includes the ASN.1 octet string header (`0410`).

**Comment by zackify** [comment]
Thanks for the reply. Is that hex okay to use for identifying the exact device? 

The problem is, in my system if I just store “yubikey 5 series device” it doesn’t help identify which key you have. Which makes it hard if you need to revoke one.

**Comment by emlun** [comment]
Sorry, it's not - 5 Nano, 5C, and 5C Nano all have the same attestation certificate and AAGUID. There is no way to determine the form factor from the FIDO attestation, except for 5 NFC which has a separate cert and AAGUID since it's functionally distinct from the other three. The YubiKey 5 series does report form factor in its device info, but it is not exposed in the FIDO attestation.

**Comment by emlun** [comment]
As for the issue of revocation:

If you mean the RP revoking due to device vulnerabilities being found, then you would want to revoke all three kinds anyway since they're functionally identical.

If you mean the user revoking individual credentials (because they got a newer security key, or lost one, etc.), then our recommendation is to allow (and encourage) the user to set their own nicknames for each of their credentials so they can tell them apart.

Hope that helps!

**Comment by zackify** [comment]
This helps a lot! Thanks

**Comment by zackify** [comment]
@emlun hey, I'm a bit of a noob, if you have time can you point me to where I can read about why the ASN.1 octet string header is added when i parse the pem?

**Comment by emlun** [comment]
Probably the WebAuthn spec, in [the section on the `id-fido-gen-ce-aaguid` X.509 extension](https://www.w3.org/TR/webauthn-2/#sctn-packed-attestation-cert-requirements). Note how the AAGUID is wrapped with an octet string header twice - this is because X.509 defines that extensions must have octet string values, and the value of the `id-fido-gen-ce-aaguid` extension is also in turn defined to be an octet string. Unfortunately, some YubiKey models have certificates where the AAGUID is erroneously wrapped only once.

**Comment by zackify** [comment]
Thanks! Really appreciate it. Makes me want to learn enough to go work at yubico when I learn this stuff 😄
