### ISSUE TITLE
Bad way of generating pin/puk on PIV/Guides/Certificate_authority

### ISSUE THREAD

**Issue by hcgrove** [Yubico/developers.yubico.com#87]
It's probably fair to assume that /dev/random will return random bytes. But making hexdump convert them to ascii codes, results in a very uneven distribution of the output values. I generated 209888 "pins" and some simple analysis on the first digit gave:
0:   840
1: 91189
2: 54919
3:  8947
4:  9079
5:  9004
6:  8936
7:  9014
8:  8952
9:  9008

**Comment by klali** [comment]
this is obviously bad. A more even distribution seems to be achievable by doing:
$ dd if=/dev/random bs=1 count=6 2>/dev/null | hexdump -v -e '/1 "%u"' | rev | cut -c1-6

This still feels like a bit of a hack but uses commonplace utilities, opinions?

**Comment by klali** [comment]
with this I get the (first character) distribution:

  57937 0
  57264 1
  57942 2
  57854 3
  57809 4
  58124 5
  55662 6
  55244 7
  55391 8
  55651 9

over 568879 values

**Comment by mdempsky** [comment]
I was reading through the documentation and discovered this same issue. I'm surprised it's been known for this long and not yet fixed.

@klali Simply reversing the bytes isn't acceptable, because digits still end up biased, just the first byte is less visibly biased. For example, the third digit is very biased though:

    $ for x in $(seq 6000); do dd if=/dev/urandom bs=1 count=6 2>/dev/null | hexdump -v -e '/1 "%u"' | rev | cut -c3; done | sort | uniq -c
        218 0
       2629 1
       1515 2
        245 3
        236 4
        248 5
        214 6
        230 7
        234 8
        231 9

As for better recommendation, according to Python's documentation, random.SystemRandom is cryptographically secure and has been present since Python 2.4 (Nov 2004):

    $ python -c 'import random; print "%06d" % random.SystemRandom().randrange(1e6)'
    093798
    $ python -c 'import random; print "%08d" % random.SystemRandom().randrange(1e8)'
    81677503

**Comment by martelletto** [comment]
using standard unix tools, wouldn't it be acceptable to rely on 
/dev/urandom's own distribution and keep reading until we obtain the 
desired number of digits? as in:

$ dd if=/dev/urandom 2>/dev/null | tr -cd '[:digit:]' | fold -w8 | head -1
38743479

-p.

**Comment by mdempsky** [comment]
@martelletto That looks good to me too.

**Comment by martelletto** [comment]
fixed in 16fdee81; thanks for the report and input!
